### ISSUE TITLE
Commented line within code block incorrectly parsed as tag

### ISSUE THREAD

**Issue by ngirard** [datopian/markdowndb#99]
Hey, happy new year and kudos for involving yourself into such a nice project !

I gave it a try today and ran into quite a few problems, which I'll try to report here. Here's the first one.

Using latest mddb on Ubuntu 23.04.

One of my notes contains
<pre>

```bash
#---------------------------------------------------------------------------------------
# Install MySQL and Dependencies
#---------------------------------------------------------------------------------------
echo -e "\\n\\n######### Installing mysql Server #########\\n\\n"
...
```
</pre>

and caused mddb to try and insert '---------------------------------------------------------------------------------------' as a tag.

**Comment by ngirard** [comment]
Also this code block
<pre>
```css
.light {
	--accent: #009a9a;
	--green: #00a229;
	--text: black;
	--foreground: #f5f5f5;
	--background: #ddd;
	--outside: #ececec;
	--post: #eee;
	--panel-border: 1px solid #ccc;
	--highlighted: white;
	--visited: #555;
	--shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}
```
</pre>
mddb to try and insert `009a9a`, `00a229`, ... as tags.
